### ISSUE TITLE
curses header files

### ISSUE THREAD

**Issue by evert-mouw** [chaos/diod#51]
To compile diod on RHEL 6.x, you also need the ncurses header files.
Please add to the red had compilation instructions:
`yum install ncurses-devel ncurses`
I still couldn't compile after that... tried to add it to the Makefile but I did something wrong. I gave up (not much time to tinker around) and comiled the older diod-1.0.23 without problems.

**Comment by nkichukov** [comment]
Hello @evert-mouw , it seems like there was an attempt to allow use of ncurses instead of curses, however, even by passing --with-ncurses configure switch, the library it links against remains -lcurses.
For dtop, linking against -lcurses is not sufficiant, it requires adding another library: -ltinfo (part of ncurses package).

The change is introduced via https://github.com/chaos/diod/commit/8bbada1983522bce0b09e8c4cc4c95e8441bc7f5

I had to apply the following patch to be able to compile the package:
[append-ltinfo.patch.txt](https://github.com/chaos/diod/files/7307170/append-ltinfo.patch.txt)

Hope this helps.
