### ISSUE TITLE
Automatically exit diod once last export has been clunked by the last client

### ISSUE THREAD

**Issue by Rudd-O** [chaos/diod#84]
Hi!  I am running automated testing of `diod` and I would like a mechanism to make `diod` exit gracefully once all clients have signaled unmount (via `clunk`) of all attached file systems.  Is this possible?  If so, how?  If not, how hard would it be to add this?

**Comment by Rudd-O** [comment]
I looked at the code and I can't find for the life of me on which data structures `diod` tracks what is mounted where.

An equivalent ask would be to ensure that some external program is called, or some log record is written, when a file system is attached or detached by a client.  This would allow me to track what `diod` is doing and exit it cleanly when done.

**Comment by garlick** [comment]
Haven't done much with diod internals in a while, so I don't have a ready answer off the top of my head.

I _think_ the data structure you are looking for is `struct Npconn` (in libnpfs).

The server can log each 9P message if you run it with `-d 1 -L filename`.

One way to get a diod process to run for the lifetime of one mount is to pass it a file descriptor representing one client instead of telling it to listen for connections.   Use the `--rfdno` / `--wfdno` diod options.  For example see `tests/kern/runtest` and `tests/kern/kconjoin.c`.

**Comment by Rudd-O** [comment]
Thanks for your kind answer!  I tracked down the issue and my client process was not closing its FDs, therefore remaining open, and keeping `diod` alive.  You are awesome.

**Comment by Rudd-O** [comment]
(This would still be a nice feature request, if you'd like to reopen it.)

**Comment by garlick** [comment]
Glad you sorted it!

May I ask what the goal of your testing is and whether your work is open source?   My intention is to redo the diod CI test suite at some point (#61, #26, etc) so maybe your work will be useful at that time?

**Comment by Rudd-O** [comment]
My work is definitely open source, and here it is: https://github.com/Rudd-O/qubes-shared-folders .  I am using `diod` as a transport between qubes, because none of the other alternatives fulfill the requirements of:

1. zero configuration
2. tiny codebase
3. easily remotable
4. easily automatable

Thanks for such an amazing project!

**Comment by garlick** [comment]
Looks quite neat!   Thanks for that.
